#!/bin/bash

# Enable and start the rclone-zettelkasten systemd user service
if command -v systemctl &>/dev/null && systemctl --user --version &>/dev/null; then
  echo "Enabling and starting rclone-zettelkasten service..."
  systemctl --user daemon-reload
  systemctl --user enable rclone-zettelkasten.service
  systemctl --user start rclone-zettelkasten.service
fi

# Install the font
if [ ! -f ~/.local/share/fonts/HackNerdFont-Regular.ttf ]; then
  echo "Install HackNerdFont"
  wget -P /tmp/ https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/Hack.zip
  unzip /tmp/Hack.zip -d ~/.local/share/fonts/
  fc-cache -vf ~/.local/share/fonts
fi

# Install neovim config
if [ ! -f ~/.config/nvim/init.lua ]; then
  echo "Installing NeoVim config"
  git clone https://github.com/Rom3dius/lazyvim-romedius ~/.config/nvim
fi
